# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 20:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('BH', 'Borehole'), ('CPT', 'CPT'), ('DCPT', 'DCPT'), ('SI', 'Inclinometer'), ('PZ', 'Piezometer'), ('SG', 'Settlement gauge'), ('TH', 'Test hole'), ('TP', 'Test pit'), ('SA', 'Sampling point')], max_length=4)),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('field_tech', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=50)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uscs', models.CharField(choices=[('CL', 'CL'), ('ML', 'ML'), ('OL', 'OL'), ('PT', 'PT'), ('SP', 'SP'), ('SW', 'SW'), ('SM', 'SM'), ('SC', 'SC'), ('GP', 'GP'), ('GW', 'GW'), ('GM', 'GM'), ('GC', 'GC'), ('SPSM', 'SP-SM'), ('GPGM', 'GP-GM'), ('CLML', 'CL-ML'), ('ROCK', 'ROCK')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_layers', to='projects.DataPoint')),
            ],
            options={
                'ordering': ['depth_from'],
            },
        ),
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('field_tech', models.CharField(max_length=50)),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='projects.DataPoint')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='datapoint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='projects.Project'),
        ),
    ]
