# Generated by Django 2.0.dev20170824180835 on 2017-09-04 19:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('CPT', 'CPT'), ('DCPT', 'DCPT'), ('SI', 'Inclinometer'), ('PZ', 'Piezometer'), ('SG', 'Settlement gauge'), ('TH', 'Test hole'), ('TP', 'Test pit')], max_length=4)),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('field_tech', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='projects.Project')),
            ],
        ),
    ]
