# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170907_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uscs', models.CharField(choices=[('CL', 'CL'), ('ML', 'ML'), ('OL', 'OL'), ('PT', 'PT'), ('SP', 'SP'), ('SW', 'SW'), ('SM', 'SM'), ('SC', 'SC'), ('GP', 'GP'), ('GW', 'GW'), ('GM', 'GM'), ('GC', 'GC'), ('SPSM', 'SP-SM'), ('GPGM', 'GP-GM'), ('CLML', 'CL-ML'), ('ROCK', 'ROCK')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('borehole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_layers', to='projects.DataPoint')),
            ],
        ),
    ]
