# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_soillayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borehole',
            name='project',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='soillayer',
            options={'ordering': ['depth_from']},
        ),
        migrations.DeleteModel(
            name='Borehole',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
