# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_soilsample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soillayer',
            old_name='borehole',
            new_name='datapoint',
        ),
        migrations.AlterField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
